/*Abrir o mycli pelo terminal - mycli -u adison -p digitar a senha*/
/*MODELAGEM LÓGICA E FÍSICA*/
/*SEGUNDA E TERCEIRA FORMAS NORMAIS*/

/*PRIMEIRA FORMA NORMAL
 - ATOMICIDADE - UM CAMPO NÃO PODE SER DIVISÍVEL, OU SEJA, MULTIVALORADO TEM QUE TER UM NŨCLEO.
 - UM CAMPO NÃO PODE SER VETORIZADO, TER UMA COLAÇÃO DE ELEMENTOS DO MESMO TIPO, COMO VARIOS TELEFONES.
 - CHAVE PRIMÁRIA PK - IDENTIFICA TODO O REGISTRO COMO SENDO ÚNICO*/

 /*SEGUNDA FORMA NORMAL
  - A UNIÃO DOS CAMPOS DE UMA TABELA, A CHAVE(S) PRIMÁRIA(S), PRECISAM SER BASE DE OUTRO ELEMENTO NÃO CHAVE.
  - OU SEJA, UM ELEMENTO NÃO CHAVE SÓ PODE EXISTIR SE TIVER VICULADO A UM ELEMENTO CHAVE.
  - DEPENDÊNCIA DIRETA.
  - TABELA ASSOCIATIVA DE CHAVES. */

 /*TERCEIRA FORMA NORMAL
  - CAMPOS NÃO CHAVE QUE DEPENDEM DE OUTROS CAMPOS NÃO CHAVE SE TRANSFORMAM EM OUTRA TABELA.
  - É APLICADO NOS CAMPOS ASSOCIATIVOS, CHAVES QUE ASSOCIAM AS TABELAS, PK.
  - DEPENDÊNCIA TRANSITIVA.
  - TABELA LIGADA A UMA TABELA ASSOCIATIVA.*/ 


/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE CONSULTORIO;

/*UTILIZANDO O BANCO CRIADO*/
USE CONSULTORIO;

/*CRIANDO TABELAS*/
CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	NASCIMENTO DATE
);

CREATE TABLE MEDICO(
	IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	ESPECIALIDADE VARCHAR(30),
	FUNCIONARIO ENUM('S', 'N')
);

CREATE TABLE HOSPITAL(
	IDHOSPITAL INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR(30),
	ESTADO CHAR(2)
);

CREATE TABLE CONSULTA(
	IDCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
	ID_PACIENTE INT,
	ID_MEDICO INT,
	ID_HOSPITAL INT,
	DATA DATETIME,
	DIAGNOSTICO VARCHAR(50)
);

CREATE TABLE INTERNACAO(
	IDINTERNACAO INT PRIMARY KEY AUTO_INCREMENT,
	ENTRADA DATETIME,
	QUARTO INT,
	SAIDA DATETIME,
	OBSERVACOES VARCHAR(50),
	ID_CONSULTA INT UNIQUE
);

/*CRIAR CONSTRAINTS - PK/FK_TABELA PERTENCE_TABELA DE ONDE VEM*/
ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_PACIENTE
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_MEDICO
FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(IDMEDICO);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_HOSPITAL
FOREIGN KEY(ID_HOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);

ALTER TABLE INTERNACAO ADD CONSTRAINT FK_INTERNACAO_CONSULTA
FOREIGN KEY(ID_CONSULTA) REFERENCES CONSULTA(IDCONSULTA);