/*Abrir o mycli pelo terminal - mycli -u adison -p digitar a senha*/
/*MODELAGEM LÓGICA E FÍSICA*/
/*ENTENDENTO TRIGGERS - GATILHO*/

/*ESTRUTURA DE UM TRIGGER - FAZ/DISPARA QUALQUER COISA ENTRE O INICIO E O FIM DO COMANDO
ANTES/BEFORE OU DEPOIS/AFTER DO COMANDO QUE PODE SER INSERT/DELETE/UPDATE DA TABELA.
É PRECISO MUDAR O DELIMITADOR ANTES COMO NAS PROCEDURES.*/
CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW/*PARA CADA LINHA*/
BEGIN -> INICIO

	QUALQUER COMANDO SQL;

END -> FIM
#

/*BANCO DE DADOS PARA TREINO*/
USE TREINAMENTO;

/*TABELA - USUÁRIO*/
CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(100)
);

/*TABELA - BACKUP*/
CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

/*ANTES DE CRIAR A TRIGGER PRECISA MUDAR O DELIMITADOR*/
DELIMITER #

/*CRIANDO A TRIGGER - OBJETIVO BACKUP DE USUARIO DELETADO, DISPARADO ANTES/BEFORE DE DELETAR*/
CREATE TRIGGER BACKUP_USUARIO
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BKP_USUARIO VALUES(NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);

END
#
DELIMITER ;

/*INSERINDO DADOS*/
INSERT INTO USUARIO VALUES(NULL, 'ANDRADE', 'ANDRADE2022', '741852321');

/*CONSULTANDO TABELA USUARIO*/
SELECT IDUSUARIO, NOME, LOGIN,SENHA
FROM USUARIO;

/*DELETANDO USUARIO*/
DELETE FROM USUARIO
WHERE IDUSUARIO = 1;

/*DELETAR A TABELA*/
DELETE FROM USUARIO;

/*CONSULTADO TABELA BACKUP USUARIO*/
SELECT * FROM BKP_USUARIO;