/*Abrir o workbanch pelo terminal - mysql -u adison -p digitar a senha*/
/*Abrir o mycli pelo terminal - mycli -u adison -p digitar a senha*/

/*PARA SE PROGRAMAR EM MYSQL É PRECISO MUDAR O DELIMITADOR.
PARA MUDAR O DELIMITADOR É PRECISO CRIAR UMA PROCEDURE COM O 
COMANDO DELIMITER + O LIMITADOR.*/

/*AO ABRIR E FECHAR O BANCO O DELIMITER VOLTA AO PADRÃO.*/

/*A PROGRAMAÇÃO EM MYSQL SERVE PARA DIVIDIR A REGRA DE NEGÓCIO
UM SISTEMA USA O PADRÃO MVC, MODEL(BANCO), VIEW(FRONT) E CONTROLER(BACK - REGRA DE NEGÓCIO)
CASO SEJA EXIGIDO PELA REGRA DE NEGÓCIO QUE ELA SEJA FEITA PELO BANCO É POSSÍVEL.
CADA BANCO DE DADOS TEM SUAS LINGUAGENS PRÓPRIAS.*/

/*A VANTAGEM/DESVANTAGEM DE SE USAR O BANCO COMO REGRA DE NEGÓCIO JUNTO COM A FUNÇÃO MODEL É A FIXAÇÃO
DO TIPO DE BANCO, POIS COMO ELA ESTÁ SERVINDO COMO REGRA DE NEGÓCIO NÃO PODE SER MUDADA
PARA OUTRO TIPO DE BANCO, POIS CADA UM TEM SEU TIPO DE LINGUAGEM.
UMA VANTAGEM É ELEVAR O NÍVEL DE PROCESSAMENTO DE CADA BANCO E DESAFOGAR O PROCESSAMENTO DOS
SISTEMAS BACK AND DA CAMADA CONTROLER.
OUTRA VANTAGEM É A FACILIDADE PARA MIGRAR DE SISTEMA BACKAND POIS A REGRA DE NEGÓCIO ESTARÁ 
NO BANCO.*/

/*BANCO DE DADOS UTILIZADO - PROJETO*/
USE PROJETO;

/*CRIANDO A TABELA*/
CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

/*INSERINDO DADOS*/
INSERT INTO CURSOS VALUES(NULL, 'C++', 30, 500.00);
INSERT INTO CURSOS VALUES(NULL, 'BANCO DE DADOS', 40, 700.00);

/*SELECIONANDO*/
SELECT * FROM CURSOS;
+---------+----------------+-------+--------+
| IDCURSO | NOME           | HORAS | VALOR  |
+---------+----------------+-------+--------+
|       1 | C++            |    30 | 500.00 |
|       2 | BANCO DE DADOS |    40 | 700.00 |
+---------+----------------+-------+--------+

/*PROCEDURES - CADASTRAR E LER OS DADOS*/
DELIMITER #
STATUS

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
						   P_HORAS INT(30),
						   P_PRECO FLOAT(10,2))

BEGIN

	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);

END
#
DELIMITER ;

/*CHAMANDO A PROCEDURE*/
CALL CAD_CURSO('SQL SERVER',35,3000.00);
CALL CAD_CURSO('JAVA',60,5000.00);
CALL CAD_CURSO('ANGULAR',55,4500.00);

/*CONSULTA DOS DADOS*/
SELECT * FROM CURSOS;

+---------+----------------+-------+---------+
| IDCURSO | NOME           | HORAS | VALOR   |				
+---------+----------------+-------+---------+
|       1 | C++            |    30 |  500.00 |
|       2 | BANCO DE DADOS |    40 |  700.00 |
|       3 | SQL SERVER     |    35 | 3000.00 |
|       4 | JAVA           |    60 | 5000.00 |
|       5 | ANGULAR        |    55 | 4500.00 |
+---------+----------------+-------+---------+
5 rows in set (0,00 sec)

/*INSERIR MAIS DADOS E CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS*/
/*INSERINDO DADOS*/
CALL CAD_CURSO('React',60,4700.00);
CALL CAD_CURSO('Arquitetura de software',85,700.00);
CALL CAD_CURSO('Oracle',40,3000.00);8
CALL CAD_CURSO('POSTGRES',35,3000.00);
CALL CAD_CURSO('C#',60,5000.00);
CALL CAD_CURSO('PYTON',50,4500.00);
CALL CAD_CURSO('JAVA SCRIPT',50,5000.00);
CALL CAD_CURSO('CSS',30,2000.00);
CALL CAD_CURSO('HTML',30,2000.00);
CALL CAD_CURSO('Docker',55,4500.00);
CALL CAD_CURSO('Git e Github',30,2000.00);
CALL CAD_CURSO('Inglês para devs',80,5300.00);

/*QUERY DE CURSOS*/
SELECT NOME, HORAS, VALOR
FROM CURSOS
WHERE NOME = 'JAVA';

/*PROCEDURE DE CONSULTA DE CURSOS*/
DELIMITER #
CREATE PROCEDURE CONSULTA_CURSOS(IN P_CURSO VARCHAR(30))
BEGIN

	SELECT NOME, HORAS, VALOR 
	FROM CURSOS
	WHERE NOME = P_CURSO;

END #
DELIMITER ;
STATUS

/*FAZENDO AS CONSULTAS POR MEIO DE PROCEDURES*/
CALL CONSULTA_CURSOS('JAVA');
CALL CONSULTA_CURSOS('C++');
CALL CONSULTA_CURSOS('React');
CALL CONSULTA_CURSOS('PYTON');
CALL CONSULTA_CURSOS('JAVA');
CALL CONSULTA_CURSOS('JAVA');
CALL CONSULTA_CURSOS('POSTGRES');

/*APAGAR UMA PROCEDURE*/
DROP PROCEDURE CONSULTA_CURSOS;

