/*Abrir o mycli pelo terminal - mycli -u adison -p digitar a senha*/
/*EXECICIO DE FIXAÇÃO*/
/*MODELAGEM LÓGICA E FÍSICA DE ACORDO COM OS REQUISITOS*/

/*BANCO DE DADOS CRIADO - TREINAMENTO*/
CREATE DATABASE OFICINA;

/*BANCO DE DADOS UTILIZADO - TREINAMENTO*/
USE OFICINA;

/*CRIAÇÃO DAS TABELAS*/
/*TABELA CLIENTE*/
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CARRO INT UNIQUE,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL
);

/*TABELA TELEFONE*/
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT,
	NUMERO VARCHAR(15) NOT NULL, 
	TIPO ENUM('RES','CEL','COM') NOT NULL
);

/*TABELA CARRO*/
CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	ID_MARCA INT UNIQUE,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE
); 

/*TABELA MARCA*/
CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

/*TABELA CORES*/
CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(10) UNIQUE
);

/*TABELA ASSOCIATIVA - CARRO_COR*/
CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO, ID_COR)
);

/*CRIANDO REGRAS/CONSTRAINTS POR FORA*/
/*FK_TABELA-ORIGEM_TABELA-DESTINO - CLIENTE_CARRO*/
ALTER TABLE CLIENTE 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO) 
REFERENCES CARRO (IDCARRO);

/*CRIANDO REGRAS/CONSTRAINTS POR FORA*/
/*FK_TABELA-ORIGEM_TABELA-DESTINO - TELEFONE_CLIENTE*/
ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE) 
REFERENCES CLIENTE (IDCLIENTE);

/*CRIANDO REGRAS/CONSTRAINTS POR FORA*/
/*FK_TABELA-ORIGEM_TABELA-DESTINO - CARRO_MARCA*/
ALTER TABLE CARRO 
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA) 
REFERENCES MARCA (IDMARCA);

/*CRIANDO REGRAS/CONSTRAINTS POR FORA*/
/*FK CARRO TABELA-ASSOCIATIVA CARRO_COR*/
ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO) 
REFERENCES CARRO (IDCARRO);

/*CRIANDO REGRAS/CONSTRAINTS POR FORA*/
/*FK COR TABELA-ASSOCIATIVA CARRO_COR*/
ALTER TABLE CARRO_COR 
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR) 
REFERENCES COR (IDCOR);


/*PREENCHER O BANCO COM 10 CLIENTES*/
/*TABELAS*/
/*         
 CARRO_COR                                            
*/
/*TABELA CARRO/MARCA*/
INSERT INTO MARCA VALUES(NULL, 'TOYOTA');
INSERT INTO CARRO VALUES(NULL, 1,'COROLA', 'BRA2E19');

INSERT INTO MARCA VALUES(NULL, 'VOLKSWAGEN');
INSERT INTO CARRO VALUES(NULL, 2,'POLO', 'FRD4486');

INSERT INTO MARCA VALUES(NULL, 'MERCEDES');
INSERT INTO CARRO VALUES(NULL, 3,'GLE', 'OTM2A18');

INSERT INTO MARCA VALUES(NULL, 'FORD');
INSERT INTO CARRO VALUES(NULL, 4,'MUSTANG', 'QOZ1772');

INSERT INTO MARCA VALUES(NULL, 'BMW');
INSERT INTO CARRO VALUES(NULL, 5,'X5', 'PLR3D97');

INSERT INTO MARCA VALUES(NULL, 'HONDA');
INSERT INTO CARRO VALUES(NULL, 6,'CITY', 'GTJ6699');

INSERT INTO MARCA VALUES(NULL, 'MITSUBISH');
INSERT INTO CARRO VALUES(NULL, 7,'OUTLANDER', 'PXL9D49');

INSERT INTO MARCA VALUES(NULL, 'HYUNDAI');
INSERT INTO CARRO VALUES(NULL, 8,'TUCSON', 'HQW6578');

INSERT INTO MARCA VALUES(NULL, 'FIAT');
INSERT INTO CARRO VALUES(NULL, 9,'ARGO', 'JHW6773');

INSERT INTO MARCA VALUES(NULL, 'CHEVROLET');
INSERT INTO CARRO VALUES(NULL, 10,'ONIX', 'BRA3R52');

/*TABELA CLIENTE*/
INSERT INTO CLIENTE VALUES(NULL, 1, 'FERNANDO SILVA', 'M');
INSERT INTO CLIENTE VALUES(NULL, 2, 'JOANA BENTO', 'F');
INSERT INTO CLIENTE VALUES(NULL, 3, 'LIANA SALES', 'F');
INSERT INTO CLIENTE VALUES(NULL, 4, 'ANDRE MOURA', 'M');
INSERT INTO CLIENTE VALUES(NULL, 5, 'LUIZ CARLOS', 'M');
INSERT INTO CLIENTE VALUES(NULL, 6, 'EDUARDO ROMEIRO', 'M');
INSERT INTO CLIENTE VALUES(NULL, 7, 'ANDERSON RIVEIRO', 'M');
INSERT INTO CLIENTE VALUES(NULL, 8, 'MATEUS JUNIOR', 'M');
INSERT INTO CLIENTE VALUES(NULL, 9, 'KATIA SOUZA', 'F');
INSERT INTO CLIENTE VALUES(NULL, 10, 'SABRINA LEMOS', 'F');

/*TABELA TELEFONE*/
INSERT INTO TELEFONE VALUES(NULL, 1, '33547419', 'RES');
INSERT INTO TELEFONE VALUES(NULL, 2, '982967410', 'CEL');
INSERT INTO TELEFONE VALUES(NULL, 3, '37418694', 'COM');
INSERT INTO TELEFONE VALUES(NULL, 4, '935479544', 'CEL');
INSERT INTO TELEFONE VALUES(NULL, 5, '979138672', 'CEL');
INSERT INTO TELEFONE VALUES(NULL, 6, '34849030', 'RES');
INSERT INTO TELEFONE VALUES(NULL, 7, '35869604', 'RES');
INSERT INTO TELEFONE VALUES(NULL, 8, '30407691', 'COM');
INSERT INTO TELEFONE VALUES(NULL, 9, '985124021', 'CEL');
INSERT INTO TELEFONE VALUES(NULL, 10, '31964200', 'RES');

/*TABELA COR*/
INSERT INTO COR VALUES(NULL, 'PRATA');
INSERT INTO COR VALUES(NULL, 'BRANCO');
INSERT INTO COR VALUES(NULL, 'PRETO');
INSERT INTO COR VALUES(NULL, 'VERMELHO');
INSERT INTO COR VALUES(NULL, 'AZUL');
INSERT INTO COR VALUES(NULL, 'VERDE');

/*TABELA CARRO_COR*/
INSERT INTO CARRO_COR VALUES(1, 2);
INSERT INTO CARRO_COR VALUES(2, 3);
INSERT INTO CARRO_COR VALUES(3, 3);
INSERT INTO CARRO_COR VALUES(4, 1);
INSERT INTO CARRO_COR VALUES(5, 5);
INSERT INTO CARRO_COR VALUES(6, 1);
INSERT INTO CARRO_COR VALUES(7, 3);
INSERT INTO CARRO_COR VALUES(8, 6);
INSERT INTO CARRO_COR VALUES(9, 1);
INSERT INTO CARRO_COR VALUES(10, 4);
