/*Abrir o mycli pelo terminal - mycli -u adison -p digitar a senha*/
/*MODELAGEM LÓGICA E FÍSICA*/
/*COMUNICAÇÃO ENTRE BANCOS E TRIGGERS PARA BANCOS DE BACKUPS*/

/*BASE DA DADOS PARA ESTUDO*/
CREATE DATABASE LOJA;

/*UTILIZAÇÃO DO BANCO*/
USE LOJA;

/*TABELA PRODUTO*/
CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

/*CRIANDO BANCO DE BACKUP*/
CREATE DATABASE BACKUP;

/*UTILIZAÇÃO DO BANCO*/
USE BACKUP;

/*TABELA DE BACKUP DE PRODUTO*/
CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

/*VOLTAR AO BANCO ORIGINAL*/
USE LOJA;

/*INSERINDO DADOS EM OUTRO BANCO*/
INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, 1000, 'TESTE', 0.0);

/*CONSULTANDO DADOS EM OUTRO BANCO*/
SELECT * FROM BACKUP.BKP_PRODUTO;

/*DISTRIBUINDO OS DADOS ENTRE BANCOS*/
/*CRIANDO DELIMITER*/
DELIMITER #

/*CRIANDO TRIGGER PARA BACKUP AO INSERIR DADOS*/
CREATE TRIGGER BACKUP_PRODUTO
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);

END #

DELIMITER ;

/*INSERINDO PRODUTOS*/
INSERT INTO PRODUTO VALUES(NULL, 'CODIGO LIMPO', 65.00);
INSERT INTO PRODUTO VALUES(NULL, 'MODELAGEM', 50.00);
INSERT INTO PRODUTO VALUES(NULL, 'ARQUITETURA LIMPA', 75.00);
INSERT INTO PRODUTO VALUES(NULL, 'LIVRO - MVC', 45.00);

/*CONSULTANDO PRODUTOS*/
SELECT * FROM PRODUTO;

/*CONSULTANDO BACKUP DE PRODUTOS*/
SELECT * FROM BACKUP.BKP_PRODUTO;

/*CRIANDO TRIGGER PARA BACKUP AO DELETAR DADOS*/
DELIMITER #
CREATE TRIGGER BACKUP_PRODUTO_DEL
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR);

END #
DELIMITER ;

/*GRAVANDO DEPOIS INSERIR DADOS*/
DELIMITER #
CREATE TRIGGER BACKUP_PRODUTO_DEPOIS
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);

END #
DELIMITER ;

/*INSERINDO PRODUTOS*/
INSERT INTO PRODUTO VALUES(NULL, 'LIVRO - JAVA', 60.00);

/*CONSULTANDO PRODUTOS*/
SELECT * FROM PRODUTO;

/*CONSULTANDO BACKUP DE PRODUTOS*/
SELECT * FROM BACKUP.BKP_PRODUTO;

/*COMPLETANDO TRIGGER PARA INFORMAR A OPERAÇÃO FEITA*/
ALTER TABLE BACKUP.BKP_PRODUTO
ADD EVENTO CHAR(1);

/*APAGANDO TRIGGER*/
DROP TRIGGER BACKUP_PRODUTO_DEL;

/*CRIANDO TRIGGER*/
DELIMITER #
CREATE TRIGGER BACKUP_PRODUTO_DEL
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR,'D');

END #
DELIMITER ;

/*DELETANDO PRODUTO*/
DELETE FROM PRODUTO WHERE IDPRODUTO = 4;

/*CONSULTANDO*/
SELECT * FROM PRODUTO;

/*CONSULTANDO NO OUTRO BANCO*/
SELECT * FROM BACKUP.BKP_PRODUTO;

/*IDENTIFICAR TRIGGER DE INSERT*/

/*DELETANDO O BANCO DE DADOS*/
DROP DATABASE LOJA;

DROP DATABASE BACKUP;